"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    try:
        audit_all_for_package(
            "scitex-bridge",
            skip_rules=(
                # PA304: `from scitex.io.bundle.kinds._stats import Position`
                # is an intentional umbrella fallback — the standalone-scitex-io
                # split removed `scitex_io.bundle.kinds._stats`. We try the
                # standalone path first, then fall back to umbrella, in
                # _stats_vis.py / _plt_vis.py / _helpers.py.
                "PA304",
                # PS140: the cross-package gate is auto-generated from
                # static `from X import Y` scans; we now use
                # `importlib.import_module(<string>)` for the umbrella
                # fallback which the auditor doesn't detect, so it flags
                # gate entries as stale. Hand-maintained for now.
                "PS140",
            ),
        )
    except TypeError:
        pytest.xfail("structural deferred; needs scitex-dev>=0.11.3 for skip_rules")
